name: Continuous Integration

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with unittest
        run: echo "::set-output name=python -m unittest discover .::$(python -m unittest discover .)"
        id: tests
      - name: Slack Messenger
        uses: joshmgross/send-slack-message@v1.0.1
        if: always()
        with:
          message: ${{ steps.tests.outputs.* }}
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ${{ secrets.SLACK_ID }}
